//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWordsRank
    {
        public System.Guid id { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> SearchCount { get; set; }
    }
}
