//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_StepInfo
    {
        public int ID { get; set; }
        public string SetpName { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsStartStep { get; set; }
        public bool IsEndStep { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public short StepResult { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ProcessTime { get; set; }
        public string Remark { get; set; }
        public int ProcessBy { get; set; }
        public int ParentStepID { get; set; }
        public int ChildStepID { get; set; }
        public int WF_InstanceID { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
